const USERS = {
  LOAD: 'USERS_LOAD',
  LOAD_SUCCESS: 'USERS_LOAD_SUCCESS',
  LOAD_FAIL: 'USERS_LOAD_FAIL',
};
const CREATE_USER = {
  START: 'CREATE_USER_START',
  SUCCESS: 'CREATE_USER_SUCCESS',
  FAIL: 'CREATE_USER_FAIL',
};
const DELETE_USER = {
  START: 'DELETE_USER_START',
  SUCCESS: 'DELETE_USER_SUCCESS',
  FAIL: 'DELETE_USER_FAIL',
};
const EDIT_USER = {
  START: 'EDIT_USER_START',
  SUCCESS: 'EDIT_USER_SUCCESS',
  FAIL: 'EDIT_USER_FAIL',
};
export { USERS, CREATE_USER, DELETE_USER, EDIT_USER };
