const USERS = {
  LOAD: 'USERS_LOAD',
  LOAD_SUCCESS: 'USERS_LOAD_SUCCESS',
  LOAD_FAIL: 'USERS_LOAD_FAIL',
};
const CREATE_USER = {
  START: 'CREATE_USER_START',
  SUCCESS: 'CREATE_USER_SUCCESS',
  FAIL: 'CREATE_USER_FAIL',
};
export { USERS, CREATE_USER };
