const USERS = {
  LOAD: 'USERS_LOAD',
  LOAD_SUCCESS: 'USERS_LOAD_SUCCESS',
  LOAD_FAIL: 'USERS_LOAD_FAIL',
};
const CREATE_USER = {
  START: 'CREATE_USER_START',
  SUCCESS: 'CREATE_USER_SUCCESS',
  FAIL: 'CREATE_USER_FAIL',
};
const DELETE_USER = {
  START: 'DELETE_USER_START',
  SUCCESS: 'DELETE_USER_SUCCESS',
  FAIL: 'DELETE_USER_FAIL',
};
const EDIT_USER = {
  START: 'EDIT_USER_START',
  SUCCESS: 'EDIT_USER_SUCCESS',
  FAIL: 'EDIT_USER_FAIL',
};
const SEARCH_USER = {
  START: 'SEARCH_USER_START',
  SUCCESS: 'SEARCH_USER_SUCCESS',
  FAIL: 'SEARCH_USER_FAIL',
};
const GET_USER = {
  START: 'GET_USER_START',
  SUCCESS: 'GET_USER_SUCCESS',
  FAIL: 'GET_USER_FAIL',
};

const NUMBER = {
  START: 'NUMBER_START',
  SUCCESS: 'NUMBER_SUCCESS',
  FAIL: 'NUMBER_FAIL',
};

const REGISTER = {
  START: 'REGISTER_START',
  SUCCESS: 'REGISTER_SUCCESS',
  FAIL: 'REGISTER_FAIL',
};
const LOGIN = {
  START: 'LOGIN_START',
  SUCCESS: 'LOGIN_SUCCESS',
  FAIL: 'LOGIN_FAIL',
};
const LOGOUT = {
  START: 'LOGOUT_START',
  SUCCESS: 'LOGOUT_SUCCESS',
  FAIL: 'LOGOUT_FAIL',
};
export { USERS, CREATE_USER, DELETE_USER, EDIT_USER, SEARCH_USER, GET_USER, NUMBER, REGISTER,LOGIN, LOGOUT };
